### PR TITLE
INSIGHT-28914: excuse bots from danger

### PR DESCRIPTION
**Pull request by sgress454**
## Description
Dependabot toils away opening up PRs and we mark them all as failures because it doesn’t open them with the correct PR titles.  And it can’t because it doesn’t open Jira issues for each PR and really, would we want it to?  Hasn't 'bendy done enough?  Let’s just skip the PR title validation for Dependabot, so we can see whether the PRs pass CI tests.

### Manual Testing 
- [X] I have manually tested this change.
Changed https://github.com/mediafly/web-client/pull/3623 to point at the new action branch, got:

image

### Automated Tests
- [ ] I have identified existing automated tests, and/or added new automated tests.
n/a

### Post-release verification
- [ ] I have documented how I will verify this change in production
will re-run the workflow on a dependabot pr and a non-dependabot PR and check that they both work.

### CODE REVIEW

**Review by sabrinajg — APPROVED** [review]
seeing green from the list of PRs will hopefully increase the frequency with which we address dependabot, which i love.

do we have a preference on 'merge dependabot's PRs one by one if they're all good' vs 'make our own branch combining a few of them'? historically it's been a bunch, but again with this change we might pay more attention and can do them more frequently.

**Review by craigforster — APPROVED** [review]

**Comment by sgress454** [comment]
> do we have a preference on 'merge dependabot's PRs one by one if they're all good' vs 'make our own branch combining a few of them'? historically it's been a bunch, but again with this change we might pay more attention and can do them more frequently.

Great question, I was wondering the same.  The only downside to doing them one at a time is the load on the CI/CD pipeline, but maybe if they show up green we'll merge them as they come so they won't build up? 🤞

**Comment by sabrinajg** [comment]
> Great question, I was wondering the same. The only downside to doing them one at a time is the load on the CI/CD pipeline, but maybe if they show up green we'll merge them as they come so they won't build up? 🤞

we can communicate a process around this, but i think our best bet is probably "if you have time to test only one, make a task, update the name, and merge from dependabot's PR. if you have a few hours of downtime and want to try to tackle a couple, pull them all into one PR"

so it becomes something you _can_ do quickly if you have 20 minutes between meetings or something, but we don't hit the pipeline hard if we want to dedicate more time to it.

**Comment by sgress454** [comment]
> we can communicate a process around this, but i think our best bet is probably "if you have time to test only one, make a task, update the name, and merge from dependabot's PR. if you have a few hours of downtime and want to try to tackle a couple, pull them all into one PR"

We can also discuss whether these always need Jira issues.  For nested dependencies (which is most of what Dependabot does) there's not often going to be a good way to test it, so there's not much value in having a Jira ticket to do prod verification on.  We could say you only need this for Dependabot PRs that actually update something in `package.json`.

**Pull request merged**
